/*
================================================================================
  DATABASE SCHEMA REVIEW
  Project : PowerAutomate-Word-to-Text (WordToHTMLX API)
  Date    : 2026-06-02
  Description:
    MSSQL database schema for persisting Word document conversions,
    SharePoint page templates, navigation configuration, and document
    comparison results generated by the WordToHTMLX API.
================================================================================
*/

-- =============================================================================
-- 1. DOCUMENTS
--    Stores uploaded Word documents (binary). ContentHash enables deduplication
--    so the same document isn't stored twice.
-- =============================================================================
CREATE TABLE Documents (
    DocumentID        INT IDENTITY(1,1) PRIMARY KEY,
    FileName          NVARCHAR(255)       NULL,
    FileSizeBytes     BIGINT              NULL,
    ContentHash       CHAR(64)            NOT NULL,   -- SHA-256
    OriginalContent   VARBINARY(MAX)      NULL,       -- raw .docx
    CreatedAt         DATETIME2           DEFAULT GETUTCDATE(),

    CONSTRAINT UQ_Documents_ContentHash UNIQUE (ContentHash)
);


-- =============================================================================
-- 2. CONVERSION REQUESTS
--    Audit log for every API call. Tracks which endpoint was hit, how long
--    it took, whether it succeeded or failed, and which document was used.
-- =============================================================================
CREATE TABLE ConversionRequests (
    RequestID         INT IDENTITY(1,1) PRIMARY KEY,
    DocumentID        INT                 NULL REFERENCES Documents(DocumentID),
    Endpoint          VARCHAR(20)         NOT NULL,   -- /api/decode | /api/section | /api/html | /api/headers | /api/compare
    TitleFilter       NVARCHAR(255)       NULL,       -- optional ?title= query param
    RequestSource     VARCHAR(50)         NULL,       -- 'raw-binary' | 'json-base64'
    Status            VARCHAR(20)         NOT NULL DEFAULT 'success',  -- success | error
    ErrorMessage      NVARCHAR(MAX)       NULL,
    ResponseSizeBytes INT                 NULL,
    ProcessingTimeMs  INT                 NULL,
    CreatedAt         DATETIME2           DEFAULT GETUTCDATE()
);


-- =============================================================================
-- 3. DOCUMENT SECTIONS
--    H1-level sections extracted from each Word document. The API splits
--    documents by H1 headings; each section becomes a row here.
-- =============================================================================
CREATE TABLE DocumentSections (
    SectionID         INT IDENTITY(1,1) PRIMARY KEY,
    DocumentID        INT                 NOT NULL REFERENCES Documents(DocumentID),
    RequestID         INT                 NULL     REFERENCES ConversionRequests(RequestID),
    SectionNumber     INT                 NOT NULL,
    Title             NVARCHAR(500)       NOT NULL,
    HtmlContent       NVARCHAR(MAX)       NULL,       -- full HTML for this section
    CreatedAt         DATETIME2           DEFAULT GETUTCDATE()
);


-- =============================================================================
-- 4. SECTION ANCHORS
--    H2 headings inside each section, used to generate the table-of-contents
--    navigation (the black button list on the right side of the page).
-- =============================================================================
CREATE TABLE SectionAnchors (
    AnchorID          INT IDENTITY(1,1) PRIMARY KEY,
    SectionID         INT                 NOT NULL REFERENCES DocumentSections(SectionID),
    HeadingText       NVARCHAR(500)       NOT NULL,
    AnchorId          VARCHAR(200)        NOT NULL,   -- slug for #hash links
    SortOrder         INT                 NOT NULL
);


-- =============================================================================
-- 5. NAVIGATION CONFIGURATION
--    Replaces the hardcoded NAVIGATION_CONFIG object in server.js. Maps each
--    section title to its previous/next/home URLs for the navigation buttons.
-- =============================================================================
CREATE TABLE NavigationConfig (
    NavID             INT IDENTITY(1,1) PRIMARY KEY,
    SectionTitle      NVARCHAR(255)       NOT NULL,
    SectionNumber     INT                 NOT NULL,
    PreviousUrl       NVARCHAR(500)       NOT NULL,
    NextUrl           NVARCHAR(500)       NOT NULL,
    HomeUrl           NVARCHAR(500)       DEFAULT '/sites/InnovationArtsEntertainment/SitePages/HANDBOOK.aspx',
    IsActive          BIT                 DEFAULT 1,
    CreatedAt         DATETIME2           DEFAULT GETUTCDATE(),
    UpdatedAt         DATETIME2           DEFAULT GETUTCDATE(),

    CONSTRAINT UQ_NavigationConfig_SectionTitle UNIQUE (SectionTitle)
);

-- Seed data matching the current hardcoded NAVIGATION_CONFIG
INSERT INTO NavigationConfig (SectionTitle, SectionNumber, PreviousUrl, NextUrl) VALUES
    ('Introduction',                  1, '/sites/InnovationArtsEntertainment/SitePages/HANDBOOK.aspx',                                       '/sites/InnovationArtsEntertainment/SitePages/Employment%20Policies%20and%20Practices.aspx'),
    ('Employment Policies and Practices', 2, '/sites/InnovationArtsEntertainment/SitePages/Introduction.aspx',                                 '/sites/InnovationArtsEntertainment/SitePages/Company%20Policies%20and%20Practices.aspx'),
    ('Company Policies and Practices',    3, '/sites/InnovationArtsEntertainment/SitePages/Employment%20Policies%20and%20Practices.aspx',      '/sites/InnovationArtsEntertainment/SitePages/Compensation%20and%20Benefits.aspx'),
    ('Compensation and Benefits',         4, '/sites/InnovationArtsEntertainment/SitePages/Company%20Policies%20and%20Practices.aspx',         '/sites/InnovationArtsEntertainment/SitePages/Work%20Performance.aspx'),
    ('Work Performance',                  5, '/sites/InnovationArtsEntertainment/SitePages/Compensation%20and%20Benefits.aspx',                '/sites/InnovationArtsEntertainment/SitePages/Department%20Guides%20and%20Procedures.aspx'),
    ('Procedures and Guidelines',         6, '/sites/InnovationArtsEntertainment/SitePages/Work%20Performance.aspx',                          '/sites/InnovationArtsEntertainment/SitePages/Employee%20Acknowledgment%20Form.aspx'),
    ('Employee Acknowledgment',           7, '/sites/InnovationArtsEntertainment/SitePages/Department%20Guides%20and%20Procedures.aspx',       '/sites/InnovationArtsEntertainment/SitePages/HANDBOOK.aspx');


-- =============================================================================
-- 6. PAGE TEMPLATES
--    Stores the SharePoint canvas JSON templates (currently hardcoded as
--    INTRO_TEMPLATE and SECTIONTEMPLATE in server.js). Allows updating
--    templates without redeploying the application.
-- =============================================================================
CREATE TABLE PageTemplates (
    TemplateID        INT IDENTITY(1,1) PRIMARY KEY,
    TemplateName      VARCHAR(50)         NOT NULL,   -- 'intro' | 'section'
    CanvasContent1    NVARCHAR(MAX)       NOT NULL,   -- JSON template string
    IsActive          BIT                 DEFAULT 1,
    CreatedAt         DATETIME2           DEFAULT GETUTCDATE(),
    UpdatedAt         DATETIME2           DEFAULT GETUTCDATE(),

    CONSTRAINT UQ_PageTemplates_TemplateName UNIQUE (TemplateName)
);


-- =============================================================================
-- 7. DOCUMENT COMPARISONS
--    Results from the /api/compare endpoint. Stores the AI-generated summary
--    of differences between two versions of a document.
-- =============================================================================
CREATE TABLE DocumentComparisons (
    ComparisonID      INT IDENTITY(1,1) PRIMARY KEY,
    LastDocumentID    INT                 NOT NULL REFERENCES Documents(DocumentID),
    CurrentDocumentID INT                 NOT NULL REFERENCES Documents(DocumentID),
    RequestID         INT                 NULL     REFERENCES ConversionRequests(RequestID),
    SummaryJSON       NVARCHAR(MAX)       NULL,       -- full AI response
    LastSizeBytes     INT                 NULL,
    CurrentSizeBytes  INT                 NULL,
    CreatedAt         DATETIME2           DEFAULT GETUTCDATE()
);


-- =============================================================================
-- 8. COMPARISON CHANGES
--    Individual change items from a comparison, each tied to a heading.
-- =============================================================================
CREATE TABLE ComparisonChanges (
    ChangeID          INT IDENTITY(1,1) PRIMARY KEY,
    ComparisonID      INT                 NOT NULL REFERENCES DocumentComparisons(ComparisonID),
    Heading           NVARCHAR(500)       NULL,
    ChangeDescription NVARCHAR(MAX)       NULL,
    SortOrder         INT                 NOT NULL
);


-- =============================================================================
-- 9. DOCUMENT IMAGES
--    Tracks {{image_url}} placeholders found in documents and their resolved
--    URLs after conversion.
-- =============================================================================
CREATE TABLE DocumentImages (
    ImageID           INT IDENTITY(1,1) PRIMARY KEY,
    DocumentID        INT                 NOT NULL REFERENCES Documents(DocumentID),
    OriginalUrl       NVARCHAR(1000)      NOT NULL,
    ResolvedUrl       NVARCHAR(1000)      NULL,
    CreatedAt         DATETIME2           DEFAULT GETUTCDATE()
);


-- =============================================================================
-- INDEXES
-- =============================================================================
CREATE INDEX IX_ConversionRequests_DocumentID  ON ConversionRequests(DocumentID);
CREATE INDEX IX_ConversionRequests_Endpoint    ON ConversionRequests(Endpoint);
CREATE INDEX IX_ConversionRequests_CreatedAt   ON ConversionRequests(CreatedAt);
CREATE INDEX IX_DocumentSections_DocumentID    ON DocumentSections(DocumentID);
CREATE INDEX IX_DocumentSections_Title         ON DocumentSections(Title);
CREATE INDEX IX_NavigationConfig_IsActive      ON NavigationConfig(IsActive);
CREATE INDEX IX_DocumentComparisons_CreatedAt  ON DocumentComparisons(CreatedAt);
CREATE INDEX IX_SectionAnchors_SectionID       ON SectionAnchors(SectionID);
CREATE INDEX IX_DocumentImages_DocumentID      ON DocumentImages(DocumentID);
